version: '3.8'

services:
  vite-app:
    build: .
    ports:
      - "5173:5173"
      - "9229:9229"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: 
      - node 
      - ./node_modules/vite/bin/vite 
      - --host 

  vite-prod:
    build: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: 
      - npm
      - run
      - build 

  npm:
    image: node:18-alpine
    volumes:
       - .:/app
    working_dir: /app
