version: '3.8'

services:
  vite-app:
    build: .
    ports:
      - "5173:5173"
      - "9229:9229"
    volumes:
      - .:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: 
      - node 
      - ./node_modules/vite/bin/vite 
      - --host 
      # - dev 

  npm:
    image: node:18-alpine
    volumes:
       - .:/app
      #  - /app/node_modules
    working_dir: /app
    # command: 
    #   -npm
